name: test_project
on: 
  push:
    branches: 
      - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get_Code
              uses: actions/checkout@v3
            - name: Install/NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test


